title: Bioversions
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  What's the current version for each biological database?

url: "https://cthoyt.com/bioversions"

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate